import * as XLSX from 'xlsx';

export const generateAndDownloadExcel = (
  productQuery: string,
  eventsText: string,
  analysisText: string
) => {
  // Try to extract EPC from the events text if the AI followed instructions
  const epcMatch = eventsText.match(/Relevant EPC: (.*?)(?:\n|$)/i);
  const inferredEPC = epcMatch ? epcMatch[1].trim() : "See Analysis";

  // Create workbook
  const wb = XLSX.utils.book_new();

  // Create data array
  const data = [
    ["EPC Trade Scout - Strategic Report"],
    ["Generated on", new Date().toLocaleDateString()],
    ["Product / Service", productQuery],
    ["Identified EPC", inferredEPC],
    [""], // Spacer
    ["STRATEGIC ANALYSIS & CALENDAR PLAN"],
    [analysisText], 
    [""], // Spacer
    ["IDENTIFIED EVENTS & EPC DETAILS"],
    [eventsText],
    [""], // Spacer
    ["Disclaimer", "Generated by AI. Verify all dates and details independently."]
  ];

  // Create worksheet from array of arrays
  const ws = XLSX.utils.aoa_to_sheet(data);

  // Styling: Set column widths
  ws['!cols'] = [
    { wch: 25 }, // Label column
    { wch: 100 } // Content column
  ];

  // Append sheet
  XLSX.utils.book_append_sheet(wb, ws, "Strategy Report");

  // Generate filename
  const filename = `Trade_Events_${productQuery.replace(/[^a-z0-9]/gi, '_').substring(0, 15)}_${new Date().getTime()}.xlsx`;

  // Write and trigger download
  XLSX.writeFile(wb, filename);
};
